### ISSUE TITLE
Question about computation resource requirements.

### ISSUE THREAD

**Issue by YecanLee** [irisdaniaj/NAS-for-Transformers#1]
Does NAS requires a lot of computation resources for trasnformer model? I remember efficient net requires a lot to do so.

**Comment by irisdaniaj** [comment]
Yes, in both the Evolved Transformer and NAS-BERT papers, even using NAS methods, the authors had to come up with different speed up and resource optimization techniques during the search of a good architecture. Unfortunately, there's no code for both papers(but the Evolved Transformer and NAS-BERT were develped by Google so they had A LOT of computational resources). ps: I dont think we can reproduce their work in our cluster :(

**Comment by YecanLee** [comment]
very sad, it would be nice if we could at least run some basic experiments to see if it is possible to do something based on the paper :(, everything is turning into a closed-source direction nowardays :(
